# Generated by Django 3.2.5 on 2022-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_employee_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateField(blank=True, default=False),
        ),
    ]
