# Generated by Django 3.2.5 on 2022-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_auto_20220318_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(blank=True, default=False),
        ),
    ]
