# Generated by Django 3.2.5 on 2022-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_alter_employee_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default=False, max_length=15),
        ),
    ]
